import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
  Sparkles,
  ArrowRight,
  ShieldCheck,
  AlertTriangle,
  Clock,
  Eye,
  Search,
  Trash2,
} from 'lucide-react';
import api from '../api/client';
import { StatusBadge } from '../components/StatusBadge';
import { LoadingSkeleton } from '../components/LoadingSkeleton';
import { EmptyState } from '../components/EmptyState';
import { useToast } from '../context/ToastContext';

export const AIReviews = () => {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const toast = useToast();

  const fetchReviews = async () => {
    try {
      setLoading(true);
      const res = await api.get('/api/reviews');
      setReviews(res.data?.reviews || []);
    } catch (err) {
      try {
        const statsRes = await api.get('/api/dashboard/stats');
        setReviews(statsRes.data?.recent_reviews || []);
      } catch (e) {
        toast.error('Failed to load reviews: ' + err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteReview = async (reviewId) => {
    if (!window.confirm(`Are you sure you want to permanently delete review #${reviewId}? This will remove all associated findings and suggestions.`)) {
      return;
    }
    try {
      await api.delete(`/api/reviews/${reviewId}`);
      toast.success(`Review #${reviewId} has been permanently deleted.`);
      setReviews((prev) => prev.filter((r) => r.id !== reviewId));
    } catch (err) {
      toast.error(err.message || 'Failed to delete review');
    }
  };

  useEffect(() => {
    fetchReviews();
  }, []);

  const filtered = reviews.filter((r) =>
    (r.listing_title || '').toLowerCase().includes(search.toLowerCase()) ||
    (r.summary || '').toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-8 space-y-6 max-w-7xl mx-auto">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">AI Compliance Reviews</h1>
          <p className="text-sm text-slate-500 mt-1">
            Browse automated policy audits generated by the AI reviewer.
          </p>
        </div>
      </div>

      {/* Demonstration Banner */}
      <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 flex items-start gap-3 text-xs text-amber-900">
        <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-bold">Demonstration Knowledge Base Active:</span> These reviews are evaluated
          against demonstration marketplace policies. Always inspect suggested revisions before applying them to
          listings.
        </div>
      </div>

      {/* Search Input */}
      <div className="relative max-w-md">
        <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
        <input
          type="text"
          placeholder="Filter reviews by title or summary..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full bg-white border border-slate-200 text-xs rounded-lg pl-9 pr-4 py-2 focus:outline-none focus:border-indigo-500"
        />
      </div>

      {/* Reviews Table */}
      {loading ? (
        <LoadingSkeleton count={4} />
      ) : filtered.length === 0 ? (
        <EmptyState
          title="No AI reviews found"
          description="Submit a listing for review from the Listings page to populate this report log."
          actionText="Go to Listings"
          onAction={() => window.location.assign('/listings')}
        />
      ) : (
        <div className="bg-white rounded-xl border border-slate-200 shadow-2xs overflow-hidden">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50/75 border-b border-slate-200 text-slate-600 font-semibold uppercase tracking-wider text-[11px]">
                <th className="py-3 px-4">Review ID</th>
                <th className="py-3 px-4">Listing Title</th>
                <th className="py-3 px-4">Findings</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Created</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.map((rev) => (
                <tr key={rev.id} className="hover:bg-slate-50/60 transition-colors">
                  <td className="py-3.5 px-4 font-mono font-semibold text-slate-700">
                    #{rev.id}
                  </td>
                  <td className="py-3.5 px-4 max-w-sm">
                    <Link
                      to={`/reviews/${rev.id}`}
                      className="font-semibold text-slate-900 hover:text-indigo-600 line-clamp-1 block"
                    >
                      {rev.listing_title || `Listing #${rev.listing_id}`}
                    </Link>
                    <p className="text-[11px] text-slate-500 line-clamp-1 mt-0.5">
                      {rev.summary}
                    </p>
                  </td>
                  <td className="py-3.5 px-4 font-medium text-slate-700">
                    <div className="flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-rose-500" title="High" />
                      <span>{rev.severity_counts?.high || 0}</span>
                      <span className="w-2 h-2 rounded-full bg-amber-500 ml-2" title="Medium" />
                      <span>{rev.severity_counts?.medium || 0}</span>
                      <span className="w-2 h-2 rounded-full bg-sky-500 ml-2" title="Low" />
                      <span>{rev.severity_counts?.low || 0}</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-4">
                    <StatusBadge status={rev.overall_status} />
                  </td>
                  <td className="py-3.5 px-4 text-slate-500 whitespace-nowrap">
                    {new Date(rev.created_at).toLocaleDateString()}
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <Link
                        to={`/reviews/${rev.id}`}
                        className="inline-flex items-center gap-1 font-semibold text-indigo-600 hover:text-indigo-800 bg-indigo-50/50 hover:bg-indigo-50 px-2.5 py-1.5 rounded text-[11px] transition"
                      >
                        View Report
                        <ArrowRight className="w-3 h-3" />
                      </Link>
                      <button
                        type="button"
                        onClick={() => handleDeleteReview(rev.id)}
                        title="Permanently delete review"
                        className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px] font-semibold text-rose-600 hover:text-rose-700 hover:bg-rose-50 border border-slate-200 hover:border-rose-200 transition"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
